services:
  frontend:
    build: 
      context: ../frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    depends_on:
      - api-service

  api-service:
    build: 
      context: ../api-service
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - AGENT_SERVICE_URL=http://agent-service:8001
      - GIT_SERVICE_URL=http://git-service:8004
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_DB=${MYSQL_DB}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - redis

  agent-service:
    build: 
      context: ../agent-service
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    environment:
      - CLAUDE_API_KEY=${CLAUDE_API_KEY}
      - GIT_SERVICE_URL=http://git-service:8004
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis

  git-service:
    build: 
      context: ../git-service
      dockerfile: Dockerfile
    ports:
      - "8004:8004"
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - GITLAB_TOKEN=${GITLAB_TOKEN}
      - REPOS_DIR=/tmp/repos
    volumes:
      - git-repos:/tmp/repos

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data:
  git-repos: