name: Deploy to Restack

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Restack Registry
        uses: docker/login-action@v2
        with:
          registry: registry.restack.io
          username: ${{ secrets.RESTACK_USERNAME }}
          password: ${{ secrets.RESTACK_PASSWORD }}

      - name: Build and push API service
        uses: docker/build-push-action@v4
        with:
          context: ./api-service
          push: true
          tags: registry.restack.io/${{ secrets.RESTACK_ORG }}/devagent/api:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Deploy API to Restack
        uses: restackio/deploy-action@v1
        with:
          token: ${{ secrets.RESTACK_TOKEN }}
          org: ${{ secrets.RESTACK_ORG }}
          project: devagent
          service: api
          image: registry.restack.io/${{ secrets.RESTACK_ORG }}/devagent/api:latest

  deploy-frontend:
    runs-on: ubuntu-latest
    needs: deploy-api
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Restack Registry
        uses: docker/login-action@v2
        with:
          registry: registry.restack.io
          username: ${{ secrets.RESTACK_USERNAME }}
          password: ${{ secrets.RESTACK_PASSWORD }}

      - name: Build and push Frontend
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          push: true
          build-args: |
            REACT_APP_API_URL=https://api.devagent.${{ secrets.RESTACK_ORG }}.restack.io
          tags: registry.restack.io/${{ secrets.RESTACK_ORG }}/devagent/frontend:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Deploy Frontend to Restack
        uses: restackio/deploy-action@v1
        with:
          token: ${{ secrets.RESTACK_TOKEN }}
          org: ${{ secrets.RESTACK_ORG }}
          project: devagent
          service: frontend
          image: registry.restack.io/${{ secrets.RESTACK_ORG }}/devagent/frontend:latest

  deploy-agent-service:
    runs-on: ubuntu-latest
    needs: deploy-api
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Restack Registry
        uses: docker/login-action@v2
        with:
          registry: registry.restack.io
          username: ${{ secrets.RESTACK_USERNAME }}
          password: ${{ secrets.RESTACK_PASSWORD }}

      - name: Build and push Agent Service
        uses: docker/build-push-action@v4
        with:
          context: ./agent-service
          push: true
          tags: registry.restack.io/${{ secrets.RESTACK_ORG }}/devagent/agent:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Deploy Agent Service to Restack
        uses: restackio/deploy-action@v1
        with:
          token: ${{ secrets.RESTACK_TOKEN }}
          org: ${{ secrets.RESTACK_ORG }}
          project: devagent
          service: agent
          image: registry.restack.io/${{ secrets.RESTACK_ORG }}/devagent/agent:latest
          env: |
            CLAUDE_API_KEY=${{ secrets.CLAUDE_API_KEY }}
            DB_CONNECTION_STRING=${{ secrets.DB_CONNECTION_STRING }}

  deploy-git-service:
    runs-on: ubuntu-latest
    needs: deploy-api
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Restack Registry
        uses: docker/login-action@v2
        with:
          registry: registry.restack.io
          username: ${{ secrets.RESTACK_USERNAME }}
          password: ${{ secrets.RESTACK_PASSWORD }}

      - name: Build and push Git Service
        uses: docker/build-push-action@v4
        with:
          context: ./git-service
          push: true
          tags: registry.restack.io/${{ secrets.RESTACK_ORG }}/devagent/git:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Deploy Git Service to Restack
        uses: restackio/deploy-action@v1
        with:
          token: ${{ secrets.RESTACK_TOKEN }}
          org: ${{ secrets.RESTACK_ORG }}
          project: devagent
          service: git
          image: registry.restack.io/${{ secrets.RESTACK_ORG }}/devagent/git:latest
          env: |
            GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
            GITLAB_TOKEN=${{ secrets.GITLAB_TOKEN }}
